# Generated by Django 5.2.9 on 2026-01-19 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunitiesBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_generated_yet", "Not Generated Yet"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("insufficient_evidence", "Insufficient Evidence"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="not_generated_yet",
                        max_length=30,
                    ),
                ),
                (
                    "ready_reason",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("opportunity_ids", models.JSONField(default=list)),
                ("evidence_summary_json", models.JSONField(default=dict)),
                ("evidence_shortfall_json", models.JSONField(default=dict)),
                ("remediation", models.TextField(blank=True, null=True)),
                ("diagnostics_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities_boards",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "hero_opportunities_board",
            },
        ),
        migrations.CreateModel(
            name="OpportunitiesJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("insufficient_evidence", "Insufficient Evidence"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=255, null=True)),
                ("available_at", models.DateTimeField(auto_now_add=True)),
                ("params_json", models.JSONField(default=dict)),
                ("result_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="hero.opportunitiesboard",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities_jobs",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "hero_opportunities_job",
            },
        ),
        migrations.CreateModel(
            name="ActivationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand_id", models.UUIDField(db_index=True)),
                ("snapshot_id", models.UUIDField()),
                ("seed_pack_json", models.JSONField(default=dict)),
                ("recipes_selected", models.JSONField(default=list)),
                ("recipes_executed", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("items_with_transcript", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_runs",
                        to="hero.opportunitiesjob",
                    ),
                ),
            ],
            options={
                "db_table": "hero_activation_run",
            },
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand_id", models.UUIDField()),
                ("platform", models.CharField(max_length=50)),
                ("actor_id", models.CharField(max_length=100)),
                ("acquisition_stage", models.PositiveSmallIntegerField()),
                ("recipe_id", models.CharField(max_length=20)),
                ("canonical_url", models.URLField(max_length=2000)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("author_ref", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("text_primary", models.TextField()),
                ("text_secondary", models.TextField(blank=True)),
                ("hashtags", models.JSONField(default=list)),
                ("view_count", models.BigIntegerField(blank=True, null=True)),
                ("like_count", models.BigIntegerField(blank=True, null=True)),
                ("comment_count", models.BigIntegerField(blank=True, null=True)),
                ("share_count", models.BigIntegerField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
                ("has_transcript", models.BooleanField(default=False)),
                ("raw_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hero.activationrun",
                    ),
                ),
            ],
            options={
                "db_table": "hero_evidence_item",
                "indexes": [
                    models.Index(
                        fields=["brand_id", "created_at"],
                        name="idx_evidence_brand_created",
                    ),
                    models.Index(
                        fields=["platform", "fetched_at"],
                        name="idx_evidence_platform_fetched",
                    ),
                    models.Index(
                        fields=["brand_id", "id"], name="idx_evidence_brand_id"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="opportunitiesboard",
            index=models.Index(
                fields=["brand", "-created_at"], name="idx_oppboard_brand_latest"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitiesboard",
            index=models.Index(
                fields=["brand", "state"], name="idx_oppboard_brand_state"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitiesjob",
            index=models.Index(
                fields=["status", "available_at"], name="idx_oppjob_status_available"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitiesjob",
            index=models.Index(
                fields=["brand", "-created_at"], name="idx_oppjob_brand_created"
            ),
        ),
        migrations.AddIndex(
            model_name="activationrun",
            index=models.Index(
                fields=["brand_id", "-started_at"], name="idx_actrun_brand_started"
            ),
        ),
        migrations.AddIndex(
            model_name="activationrun",
            index=models.Index(
                fields=["job", "-started_at"], name="idx_actrun_job_started"
            ),
        ),
    ]
