# Generated by Django 5.2.9 on 2026-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0001_pr3_sourceactivation_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitiesjob",
            name="progress_detail",
            field=models.CharField(
                blank=True,
                help_text="Human-readable progress detail (e.g., 'Processing 45 evidence items...')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunitiesjob",
            name="progress_stage",
            field=models.CharField(
                default="pending",
                help_text="Current execution stage for progress indicators",
                max_length=50,
            ),
        ),
    ]
