# Generated by Django 5.2.9 on 2025-12-23 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptureRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="running",
                        max_length=50,
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ingestion_capture_run",
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cluster_key_type", models.CharField(max_length=50)),
                ("cluster_key", models.CharField(max_length=500)),
                ("display_name", models.CharField(max_length=500)),
                ("platforms", models.JSONField(blank=True, default=list)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ingestion_cluster",
                "indexes": [
                    models.Index(
                        fields=["cluster_key_type", "last_seen_at"],
                        name="ingestion_c_cluster_cab30b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cluster_key_type", "cluster_key"),
                        name="uniq_cluster_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("platform_item_id", models.CharField(max_length=255)),
                ("item_type", models.CharField(max_length=50)),
                ("author_id", models.CharField(blank=True, max_length=255)),
                ("author_handle", models.CharField(blank=True, max_length=255)),
                ("text_content", models.TextField(blank=True)),
                ("audio_id", models.CharField(blank=True, max_length=255)),
                ("audio_title", models.CharField(blank=True, max_length=500)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("view_count", models.BigIntegerField(blank=True, null=True)),
                ("like_count", models.BigIntegerField(blank=True, null=True)),
                ("comment_count", models.BigIntegerField(blank=True, null=True)),
                ("share_count", models.BigIntegerField(blank=True, null=True)),
                ("item_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("canonical_url", models.URLField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capture_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ingestion.capturerun",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_evidence_item",
            },
        ),
        migrations.CreateModel(
            name="NormalizedArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("normalized_text", models.TextField(blank=True)),
                ("engagement_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact",
                        to="ingestion.evidenceitem",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_normalized_artifact",
            },
        ),
        migrations.CreateModel(
            name="ArtifactClusterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        max_length=20,
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("audio_id", "Audio ID"),
                            ("hashtag", "Hashtag"),
                            ("phrase", "Phrase"),
                            ("entity", "Entity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key_value", models.CharField(blank=True, max_length=500)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifact_links",
                        to="ingestion.cluster",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_links",
                        to="ingestion.normalizedartifact",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_artifact_cluster_link",
            },
        ),
        migrations.CreateModel(
            name="Surface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("surface_type", models.CharField(max_length=100)),
                ("surface_key", models.CharField(blank=True, max_length=255)),
                ("is_enabled", models.BooleanField(default=True)),
                ("cadence_minutes", models.PositiveIntegerField(default=60)),
                ("last_capture_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ingestion_surface",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "surface_type", "surface_key"),
                        name="uniq_surface_identity",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="capturerun",
            name="surface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="ingestion.surface",
            ),
        ),
        migrations.CreateModel(
            name="TrendCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emerging", "Emerging"),
                            ("active", "Active"),
                            ("peaked", "Peaked"),
                            ("stale", "Stale"),
                        ],
                        default="emerging",
                        max_length=50,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("peaked_at", models.DateTimeField(blank=True, null=True)),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("trend_score", models.FloatField(default=0)),
                ("velocity_score", models.FloatField(default=0)),
                ("breadth_score", models.FloatField(default=0)),
                ("novelty_score", models.FloatField(default=0)),
                ("last_emitted_at", models.DateTimeField(blank=True, null=True)),
                ("emit_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trend_candidates",
                        to="ingestion.cluster",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_trend_candidate",
            },
        ),
        migrations.CreateModel(
            name="ClusterBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bucket_start", models.DateTimeField()),
                ("bucket_end", models.DateTimeField()),
                ("artifact_count", models.PositiveIntegerField(default=0)),
                ("unique_authors", models.PositiveIntegerField(default=0)),
                ("total_views", models.BigIntegerField(default=0)),
                ("total_engagement", models.BigIntegerField(default=0)),
                ("avg_engagement_score", models.FloatField(default=0)),
                ("velocity", models.FloatField(default=0)),
                ("acceleration", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="ingestion.cluster",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_cluster_bucket",
                "indexes": [
                    models.Index(
                        fields=["bucket_start", "velocity"],
                        name="ingestion_c_bucket__c022e1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cluster", "bucket_start"), name="uniq_cluster_bucket"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["platform", "audio_id"], name="ingestion_e_platfor_32e3e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["platform", "captured_at"],
                name="ingestion_e_platfor_e25c0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["capture_run", "created_at"],
                name="ingestion_e_capture_01413d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceitem",
            constraint=models.UniqueConstraint(
                fields=("platform", "platform_item_id"), name="uniq_platform_item"
            ),
        ),
        migrations.AddIndex(
            model_name="artifactclusterlink",
            index=models.Index(
                fields=["cluster", "created_at"], name="ingestion_a_cluster_cf6217_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifactclusterlink",
            index=models.Index(
                fields=["artifact", "role"], name="ingestion_a_artifac_d10dff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactclusterlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("artifact",),
                name="uniq_artifact_primary_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactclusterlink",
            constraint=models.UniqueConstraint(
                fields=("artifact", "cluster", "role"),
                name="uniq_artifact_cluster_role",
            ),
        ),
        migrations.AddIndex(
            model_name="capturerun",
            index=models.Index(
                fields=["surface", "started_at"], name="ingestion_c_surface_73db8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capturerun",
            index=models.Index(
                fields=["status", "started_at"], name="ingestion_c_status_df0806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendcandidate",
            index=models.Index(
                fields=["status", "trend_score"], name="ingestion_t_status_4d8c00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendcandidate",
            index=models.Index(
                fields=["detected_at"], name="ingestion_t_detecte_55d505_idx"
            ),
        ),
    ]
