# Generated by Django 5.2.9 on 2026-01-12 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandBrainOverrides",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overrides_json", models.JSONField(default=dict)),
                ("pinned_paths", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brandbrain_overrides",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "BrandBrain Overrides",
                "verbose_name_plural": "BrandBrain Overrides",
                "db_table": "brandbrain_overrides",
            },
        ),
        migrations.CreateModel(
            name="BrandOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Tier 0 - Required"),
                            (1, "Tier 1 - Recommended"),
                            (2, "Tier 2 - Optional"),
                        ],
                        default=0,
                    ),
                ),
                ("answers_json", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Onboarding",
                "verbose_name_plural": "Brand Onboardings",
                "db_table": "brandbrain_onboarding",
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criteria_json", models.JSONField(default=dict)),
                ("item_ids", models.JSONField(default=list)),
                ("summary_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_bundles",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brandbrain_evidence_bundle",
            },
        ),
        migrations.CreateModel(
            name="BrandBrainCompileRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("onboarding_snapshot_json", models.JSONField(default=dict)),
                ("prompt_version", models.CharField(default="v1", max_length=50)),
                ("model", models.CharField(default="gpt-4", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("draft_json", models.JSONField(default=dict)),
                ("qa_report_json", models.JSONField(default=dict)),
                ("evidence_status_json", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compile_runs",
                        to="core.brand",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compile_runs",
                        to="brandbrain.evidencebundle",
                    ),
                ),
            ],
            options={
                "db_table": "brandbrain_compile_run",
            },
        ),
        migrations.CreateModel(
            name="FeatureReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stats_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_reports",
                        to="core.brand",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_reports",
                        to="brandbrain.evidencebundle",
                    ),
                ),
            ],
            options={
                "db_table": "brandbrain_feature_report",
            },
        ),
        migrations.CreateModel(
            name="NormalizedEvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("reel", "Reel"),
                            ("text_post", "Text Post"),
                            ("short_video", "Short Video"),
                            ("video", "Video"),
                            ("web_page", "Web Page"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("canonical_url", models.URLField(max_length=2000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("author_ref", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("text_primary", models.TextField()),
                ("text_secondary", models.TextField(blank=True, null=True)),
                ("hashtags", models.JSONField(default=list)),
                ("metrics_json", models.JSONField(default=dict)),
                ("media_json", models.JSONField(default=dict)),
                ("raw_refs", models.JSONField(default=list)),
                ("flags_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_evidence",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brandbrain_normalized_evidence_item",
            },
        ),
        migrations.CreateModel(
            name="SourceConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("posts", "Posts"),
                            ("reels", "Reels"),
                            ("company_posts", "Company Posts"),
                            ("profile_posts", "Profile Posts"),
                            ("profile_videos", "Profile Videos"),
                            ("channel_videos", "Channel Videos"),
                            ("crawl_pages", "Crawl Pages"),
                        ],
                        max_length=30,
                    ),
                ),
                ("identifier", models.CharField(max_length=500)),
                ("is_enabled", models.BooleanField(default=True)),
                ("settings_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_connections",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brandbrain_source_connection",
            },
        ),
        migrations.CreateModel(
            name="BrandBrainSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_json", models.JSONField(default=dict)),
                ("diff_from_previous_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brandbrain_snapshots",
                        to="core.brand",
                    ),
                ),
                (
                    "compile_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="brandbrain.brandbraincompilerun",
                    ),
                ),
            ],
            options={
                "db_table": "brandbrain_snapshot",
                "indexes": [
                    models.Index(
                        fields=["brand", "-created_at"],
                        name="idx_snapshot_brand_latest",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="evidencebundle",
            index=models.Index(
                fields=["brand", "-created_at"], name="idx_bundle_brand_created"
            ),
        ),
        migrations.AddIndex(
            model_name="brandbraincompilerun",
            index=models.Index(
                fields=["brand", "-created_at"], name="idx_compile_brand_latest"
            ),
        ),
        migrations.AddIndex(
            model_name="featurereport",
            index=models.Index(
                fields=["brand", "-created_at"], name="idx_feature_brand_created"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedevidenceitem",
            index=models.Index(
                fields=["brand", "platform", "content_type", "-created_at"],
                name="idx_nei_brand_recency",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedevidenceitem",
            index=models.Index(
                fields=["brand", "platform"], name="idx_nei_brand_platform"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceconnection",
            index=models.Index(
                fields=["brand", "is_enabled"], name="idx_source_brand_enabled"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconnection",
            constraint=models.UniqueConstraint(
                fields=("brand", "platform", "capability", "identifier"),
                name="uniq_source_brand_platform_cap_id",
            ),
        ),
    ]
