# Generated by Django 5.2.9 on 2026-01-05 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApifyRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.CharField(max_length=255)),
                ("input_json", models.JSONField(default=dict)),
                ("apify_run_id", models.CharField(max_length=255, unique=True)),
                ("dataset_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed Out"),
                            ("aborted", "Aborted"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "apify_run",
                "indexes": [
                    models.Index(
                        fields=["actor_id", "-created_at"],
                        name="apify_run_actor_i_e5d7a4_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="apify_run_status_f0501e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RawApifyItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_index", models.PositiveIntegerField()),
                ("raw_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apify_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="apify.apifyrun",
                    ),
                ),
            ],
            options={
                "db_table": "apify_raw_item",
                "indexes": [
                    models.Index(
                        fields=["apify_run", "item_index"],
                        name="apify_raw_i_apify_r_449e71_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("apify_run", "item_index"), name="uniq_run_item_index"
                    )
                ],
            },
        ),
    ]
