# Generated by Django 5.2.9 on 2026-01-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apifyrun",
            name="brand_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="apifyrun",
            name="normalized_item_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apifyrun",
            name="raw_item_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apifyrun",
            name="source_connection_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="apifyrun",
            index=models.Index(
                fields=["brand_id", "status"], name="idx_apifyrun_brand_status"
            ),
        ),
    ]
