# Generated by Django 5.2.9 on 2025-12-11 00:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "primary_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("channels", models.JSONField(blank=True, default=list)),
                ("positioning", models.TextField(blank=True)),
                ("tone_tags", models.JSONField(blank=True, default=list)),
                ("taboos", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "brand",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenant",
            },
        ),
        migrations.CreateModel(
            name="ContentPillar",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("priority_rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pillars",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "content_pillar",
            },
        ),
        migrations.CreateModel(
            name="PatternTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("evergreen", "Evergreen"),
                            ("launch", "Launch"),
                            ("education", "Education"),
                            ("engagement", "Engagement"),
                        ],
                        default="evergreen",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("experimental", "Experimental"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("beats", models.JSONField(default=list)),
                ("supported_channels", models.JSONField(default=list)),
                ("example_snippet", models.TextField(blank=True)),
                ("performance_hint", models.TextField(blank=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("avg_engagement_score", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patterns",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "pattern_template",
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("priorities", models.JSONField(blank=True, default=list)),
                ("pains", models.JSONField(blank=True, default=list)),
                ("success_metrics", models.JSONField(blank=True, default=list)),
                ("channel_biases", models.JSONField(blank=True, default=dict)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personas",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "persona",
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend"),
                            ("evergreen", "Evergreen"),
                            ("competitive", "Competitive"),
                            ("campaign", "Campaign"),
                        ],
                        max_length=50,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("score_explanation", models.TextField(blank=True)),
                ("title", models.CharField(max_length=500)),
                ("angle", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                (
                    "primary_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=50,
                    ),
                ),
                ("suggested_channels", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_snoozed", models.BooleanField(default=False)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("created_by_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("ai_suggested", "AI Suggested"),
                            ("imported", "Imported"),
                        ],
                        default="ai_suggested",
                        max_length=50,
                    ),
                ),
                ("last_touched_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="core.brand",
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="core.contentpillar",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="core.persona",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "opportunities",
                "db_table": "opportunity",
            },
        ),
        migrations.CreateModel(
            name="ContentPackage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("channels", models.JSONField(blank=True, default=list)),
                ("planned_publish_start", models.DateTimeField(blank=True, null=True)),
                ("planned_publish_end", models.DateTimeField(blank=True, null=True)),
                ("owner_user_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("ai_suggested", "AI Suggested"),
                            ("imported", "Imported"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("metrics_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="core.brand",
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="core.contentpillar",
                    ),
                ),
                (
                    "origin_opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="core.opportunity",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="core.persona",
                    ),
                ),
            ],
            options={
                "db_table": "content_package",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brands",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("raw_prompt_context", models.JSONField(blank=True, default=dict)),
                ("draft_text", models.TextField(blank=True)),
                ("edited_text", models.TextField(blank=True)),
                ("approved_text", models.TextField(blank=True)),
                ("generated_by_model", models.CharField(blank=True, max_length=100)),
                (
                    "proposed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("scheduled_publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("eval_score", models.FloatField(blank=True, null=True)),
                ("eval_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="core.brand",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.contentpackage",
                    ),
                ),
                (
                    "pattern_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="core.patterntemplate",
                    ),
                ),
            ],
            options={
                "db_table": "variant",
            },
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            (
                                "pattern_performance_update",
                                "Pattern Performance Update",
                            ),
                            ("opportunity_score_update", "Opportunity Score Update"),
                            ("channel_preference_update", "Channel Preference Update"),
                            ("guardrail_violation", "Guardrail Violation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("derived_from", models.JSONField(blank=True, default=list)),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_events",
                        to="core.brand",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events",
                        to="core.opportunity",
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events",
                        to="core.patterntemplate",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events",
                        to="core.variant",
                    ),
                ),
            ],
            options={
                "db_table": "learning_event",
            },
        ),
        migrations.CreateModel(
            name="ExecutionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("click", "Click"),
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("save", "Save"),
                            ("profile_visit", "Profile Visit"),
                            ("link_click", "Link Click"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("opportunity_pinned", "Opportunity pinned"),
                            ("opportunity_snoozed", "Opportunity snoozed"),
                            ("opportunity_ignored", "Opportunity ignored"),
                            ("package_created", "Package created"),
                            ("package_approved", "Package approved"),
                            ("variant_edited", "Variant edited"),
                            ("variant_approved", "Variant approved"),
                            ("variant_rejected", "Variant rejected"),
                        ],
                        help_text="User decision type, if this event represents a user action",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("event_value", models.TextField(blank=True)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("platform_webhook", "Platform Webhook"),
                            ("csv_import", "CSV Import"),
                            ("manual_entry", "Manual Entry"),
                            ("test_fixture", "Test Fixture"),
                        ],
                        max_length=50,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_events",
                        to="core.brand",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_events",
                        to="core.variant",
                    ),
                ),
            ],
            options={
                "db_table": "execution_event",
            },
        ),
        migrations.CreateModel(
            name="BrandSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_at",
                    models.DateTimeField(
                        help_text="Point in time this snapshot represents"
                    ),
                ),
                ("positioning_summary", models.TextField(blank=True)),
                ("tone_descriptors", models.JSONField(default=list)),
                ("taboos", models.JSONField(default=list)),
                ("pillars", models.JSONField(default=list)),
                ("personas", models.JSONField(default=list)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_snapshot",
                "indexes": [
                    models.Index(
                        fields=["brand", "snapshot_at"],
                        name="brand_snaps_brand_i_0bca33_idx",
                    ),
                    models.Index(
                        fields=["brand", "created_at"],
                        name="brand_snaps_brand_i_28f20e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentpillar",
            index=models.Index(
                fields=["brand", "is_active"], name="content_pil_brand_i_38939b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpillar",
            index=models.Index(
                fields=["brand", "created_at"], name="content_pil_brand_i_895ea2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentpillar",
            constraint=models.UniqueConstraint(
                fields=("brand", "name"), name="unique_pillar_brand_name"
            ),
        ),
        migrations.AddIndex(
            model_name="patterntemplate",
            index=models.Index(
                fields=["brand", "status"], name="pattern_tem_brand_i_99a3a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patterntemplate",
            index=models.Index(
                fields=["brand", "category"], name="pattern_tem_brand_i_473d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patterntemplate",
            index=models.Index(
                fields=["brand", "created_at"], name="pattern_tem_brand_i_184f23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(
                fields=["brand", "created_at"], name="persona_brand_i_f07485_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.UniqueConstraint(
                fields=("brand", "name"), name="unique_persona_brand_name"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["brand", "created_at"], name="opportunity_brand_i_cc1d06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["brand", "is_pinned", "is_snoozed"],
                name="opportunity_brand_i_bdcc2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["brand", "type"], name="opportunity_brand_i_2edc64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpackage",
            index=models.Index(
                fields=["brand", "status"], name="content_pac_brand_i_15a670_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpackage",
            index=models.Index(
                fields=["brand", "created_at"], name="content_pac_brand_i_d65cf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["tenant", "created_at"], name="brand_tenant__84ed58_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="uniq_tenant_brand_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["package", "channel"], name="variant_package_b97e9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["package", "created_at"], name="variant_package_a3139c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["brand", "status"], name="variant_brand_i_769524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["brand", "channel", "status"], name="variant_brand_i_f1a97c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["brand", "created_at"], name="variant_brand_i_3e2be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningevent",
            index=models.Index(
                fields=["brand", "signal_type"], name="learning_ev_brand_i_b5b35c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningevent",
            index=models.Index(
                fields=["brand", "effective_at"], name="learning_ev_brand_i_c48df6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningevent",
            index=models.Index(
                fields=["brand", "created_at"], name="learning_ev_brand_i_88007e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionevent",
            index=models.Index(
                fields=["variant", "event_type"], name="execution_e_variant_8bcdf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionevent",
            index=models.Index(
                fields=["brand", "occurred_at"], name="execution_e_brand_i_3d1e56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionevent",
            index=models.Index(
                fields=["brand", "created_at"], name="execution_e_brand_i_454dc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionevent",
            index=models.Index(
                fields=["channel", "event_type", "occurred_at"],
                name="execution_e_channel_925ce4_idx",
            ),
        ),
    ]
