# Generated by Django 5.2.9 on 2026-01-20 01:49
"""
Data migration: Rename test brand from 'RevOps Intelligence' to 'Goodie AI'.

This ensures the test brand matches the real onboarding data that has been
connected. The brand ID d8dca5da-6ee2-40a9-bd1d-4a8a065cf556 was created
with demo data initially and now reflects actual Goodie AI content.
"""

from django.db import migrations


BRAND_ID = "d8dca5da-6ee2-40a9-bd1d-4a8a065cf556"
OLD_NAME = "RevOps Intelligence"
NEW_NAME = "Goodie AI"
NEW_SLUG = "goodie-ai"


def rename_brand_forward(apps, schema_editor):
    """Rename brand from RevOps Intelligence to Goodie AI."""
    Brand = apps.get_model("core", "Brand")
    try:
        brand = Brand.objects.get(id=BRAND_ID)
        brand.name = NEW_NAME
        brand.slug = NEW_SLUG
        brand.save(update_fields=["name", "slug"])
    except Brand.DoesNotExist:
        # Brand doesn't exist yet (fresh DB) - that's fine, skip
        pass


def rename_brand_reverse(apps, schema_editor):
    """Revert brand name back to RevOps Intelligence."""
    Brand = apps.get_model("core", "Brand")
    try:
        brand = Brand.objects.get(id=BRAND_ID)
        brand.name = OLD_NAME
        brand.slug = "eval-revops-saas"
        brand.save(update_fields=["name", "slug"])
    except Brand.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_brand_forward, rename_brand_reverse),
    ]
