# Generated by Django 5.2.9 on 2026-01-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_revops_to_goodie_ai"),
        ("users", "0001_create_user_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this brand",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_brands",
                to="users.user",
            ),
        ),
    ]
