# Generated by Django 5.2.9 on 2026-01-22 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_rename_revops_to_goodie_ai"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "supabase_uid",
                    models.CharField(
                        help_text="Unique identifier from Supabase Auth",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "kairo_user",
            },
        ),
        migrations.CreateModel(
            name="UserAPIKeys",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("apify_token_encrypted", models.BinaryField(blank=True, null=True)),
                ("openai_key_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "apify_token_last4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "openai_key_last4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "apify_token_validated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "openai_key_validated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User API Keys",
                "verbose_name_plural": "User API Keys",
                "db_table": "kairo_user_api_keys",
            },
        ),
    ]
