"""
SourceActivation Types.

PR-4: Fixture-only SourceActivation.
Per opportunities_v1_prd.md Section A (SeedPack) and B.5 (EvidenceBundle).

Dataclasses for SourceActivation module:
- SeedPack: Deterministic derivation from BrandBrainSnapshot
- EvidenceItemData: Single evidence item (maps to hero.EvidenceItem)
- EvidenceBundle: Collection of evidence items
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal
from uuid import UUID


@dataclass
class SeedPack:
    """
    Deterministic seed pack derived from BrandBrainSnapshot.

    Per PRD Section A:
    - Input: BrandBrainSnapshot
    - Output: Deterministic SeedPack for actor inputs
    - Contains: Search terms derived from brand context

    Used by SourceActivation to configure evidence collection.
    In fixture-only mode, this is used for deterministic ID generation.

    QUERY PLANNER INTEGRATION:
    - tiktok_queries/instagram_queries: LLM-generated semantic search probes
    - These replace naive brand-name searches with intent-based queries
    - Generated by query_planner.generate_query_plan() during derive_seed_pack()
    """

    brand_id: UUID
    brand_name: str
    positioning: str | None = None
    # Key search terms derived from brand context
    search_terms: list[str] = field(default_factory=list)
    # Pillar keywords for topic matching
    pillar_keywords: list[str] = field(default_factory=list)
    # Persona context for relevance filtering
    persona_contexts: list[str] = field(default_factory=list)
    # Snapshot ID this was derived from
    snapshot_id: UUID | None = None

    # Query Planner outputs (LLM-generated semantic search probes)
    tiktok_queries: list[str] = field(default_factory=list)
    tiktok_hashtags: list[str] = field(default_factory=list)
    instagram_queries: list[str] = field(default_factory=list)
    instagram_hashtags: list[str] = field(default_factory=list)
    query_plan_error: str | None = None

    # Phase 3: LLM-inferred industry for TikTok Trends Scraper
    # Maps to TikTok Creative Center industry filters (e.g., "Technology", "Beauty & Personal Care")
    inferred_industry: str | None = None

    # Phase 3: Trending hashtags discovered by TT-TRENDS recipes
    # These are passed to TT-1 for content scraping with transcripts
    # Populated dynamically during execution (TT-TRENDS → TT-1 chain)
    trending_hashtags: list[str] = field(default_factory=list)


@dataclass
class EvidenceItemData:
    """
    Single evidence item data.

    Maps to hero.models.EvidenceItem but is a plain dataclass
    for passing around before persistence.

    Per PRD D.3.2 and B.5 field requirements.
    """

    # Source identification
    platform: str  # instagram, tiktok, youtube, linkedin
    actor_id: str  # Apify actor ID (or "FIXTURE" for fixture mode)
    acquisition_stage: int  # 1 or 2
    recipe_id: str  # e.g., "IG-1", "TT-1", "FIXTURE"

    # Content identification
    canonical_url: str
    external_id: str  # Platform-specific ID
    author_ref: str  # Username or handle
    title: str = ""

    # Content
    text_primary: str = ""  # Caption, body, description
    text_secondary: str = ""  # Transcript (high-value signal)
    hashtags: list[str] = field(default_factory=list)

    # Metrics (all optional)
    view_count: int | None = None
    like_count: int | None = None
    comment_count: int | None = None
    share_count: int | None = None

    # Timestamps
    published_at: datetime | None = None
    fetched_at: datetime | None = None

    # Quality flags
    has_transcript: bool = False

    # Raw payload (for debugging)
    raw_json: dict = field(default_factory=dict)


@dataclass
class EvidenceBundle:
    """
    Bundle of evidence items from SourceActivation.

    Per PRD B.5:
    - Contains normalized evidence items
    - Tracks acquisition metadata
    - Used to generate signals for opportunity synthesis

    Note: This is separate from brandbrain.EvidenceBundle which is
    for BrandBrain compilation. This is for opportunities generation.
    """

    brand_id: UUID
    activation_run_id: UUID | None = None
    snapshot_id: UUID | None = None

    # Evidence items
    items: list[EvidenceItemData] = field(default_factory=list)

    # Metadata
    mode: Literal["fixture_only", "live_cap_limited"] = "fixture_only"
    recipes_executed: list[str] = field(default_factory=list)
    fetched_at: datetime | None = None

    # Summary stats
    item_count: int = 0
    items_with_transcript: int = 0

    def __post_init__(self):
        """Compute summary stats after initialization."""
        self.item_count = len(self.items)
        self.items_with_transcript = sum(1 for item in self.items if item.has_transcript)
